baseURL = "http://grimoireunbound.github.io/"
languageCode = "en-us"
title = "Grimoire Unbound"
theme = "ananke"
publishdir = "docs"

[params]
mainSections = ["GURPS (4e)", "D&D (3.5e)"]

[menu]

[[menu.main]]
identifier = "GURPS (4e)"
name = "GURPS (4e)"
pre = "<i class='fa fa-heart'></i>"
url = "/gurps-4/"
weight = -110

[[menu.main]]
identifier = "D&D (3.5e)"
name = "D&D (3.5e)"
pre = "<i class='fa fa-heart'></i>"
url = "/dnd-3.5/"
weight = -110
